version: '3.1'

services:
  flask:
    container_name: jarmip
    environment:
      - PORT=8080
    build:
        context: .
        dockerfile: Dockerfile
    image: jarmip
    restart: always
    ports:
      - 8080:8080